### ISSUE TITLE
Convert FE to Typescript project

### ISSUE THREAD

**Issue by rsbrowne** [euanwm/OpenWeightlifting#136]
Working in JS without Types is a pain these days. For a better dev experience and making everything less prone to errors I suggest we convert this to a Typescript project

**Comment by euanwm** [comment]
Is this something we can change file-by-file or would it need to be a complete overhaul?

**Comment by rsbrowne** [comment]
The whole project would have it installed but you can then convert each JS file one by one. I worked on a project at my last company where we switched to TS and it took us about a week to convert all the files but we're talking thousands of files so it's not a huge job
