### ISSUE TITLE
TS and api refactor

### ISSUE THREAD

**Issue by mountclear** [euanwm/OpenWeightlifting#192]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mountclear** [comment]
Can I have permission to be a collaborator please:
FYI:
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

**Comment by mountclear** [comment]
So I can easily branch off and update easily too

**Comment by euanwm** [comment]
> So I can easily branch off and update easily too

@mountclear done
