### ISSUE TITLE
Benchmarking - Bun vs. Node 

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#228]
Would be interesting to trial Bun as a drop-in replacement on the frontend side of things to see if it improves response / loading times for the frontend.

**Comment by euanwm** [comment]
Bun Site: https://bun.sh/

**Comment by mountclear** [comment]
loks like you can run nextjs with Bun, might need to instantiate a new app with it though:
https://bun.sh/guides/ecosystem/nextjs

**Comment by mountclear** [comment]
Got it working with Bun:
<img width="1920" alt="Screenshot 2023-09-12 at 21 52 31" src="https://github.com/euanwm/OpenWeightlifting/assets/15941063/f32e829c-faec-41eb-bd74-2ec7e4f21099">

<img width="1920" alt="Screenshot 2023-09-12 at 21 52 47" src="https://github.com/euanwm/OpenWeightlifting/assets/15941063/cfe5f066-25fe-4831-b3ca-db4e9ec79beb">

**Comment by mountclear** [comment]
The Bun version is it's own folder call frontend-bun, will try perform metrics another day

**Comment by mountclear** [comment]
also had to disable this as it was breakign the whole app:
import { hotjar } from 'react-hotjar'

**Comment by euanwm** [comment]
Yeah that hotjar is a bit of vanilla JS if I remember.

**Comment by euanwm** [comment]
Tested and closed by #229
