### ISSUE TITLE
Define clear contribution guidelines

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#244]
Define a clear approach to contributing to this repo.

Top level ideas:

- Squash & merge for PRs
- Branch naming to be fix, chore, feature, and db.
- Tests are not strictly required but nice to have.
- Issues can be raised but templates must be followed.
- Discord channel to be used for discussions.

**Comment by Veerhan-glitch** [comment]
hey can u assign it to me?
