### ISSUE TITLE
Decrease render time on initial load

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#245]
**Is your feature request related to a problem? Please describe.**
On an initial load of the main landing page, a large amount of time is spent loading the logo within the header bar.

**Describe the solution you'd like**
Implement lazy loading for the OWL logo so that it scores higher on PageSpeed Insights

**Additional context**
![Screenshot from 2023-10-01 09-55-12](https://github.com/euanwm/OpenWeightlifting/assets/69640923/f6d0b48d-6695-42f9-b141-714ddf8dfa65)
![image](https://github.com/euanwm/OpenWeightlifting/assets/69640923/3f4b95b9-325d-4807-9210-8e5c1ea1479c)

**Comment by inomag** [comment]
Hey, can I work on this?

**Comment by euanwm** [comment]
@inomag sure

**Comment by inomag** [comment]
Hi, @euanwm Can you check this. I am not able to run the project on my system to check the update LCP score.
https://github.com/euanwm/OpenWeightlifting/pull/251

**Comment by rsbrowne** [comment]
Hey @inomag, not sure if you're still working on this but given that the image being loaded is using `next/image` I would recommend simply adding the `priority` attribute to the Image tag (see docs [here](https://nextjs.org/docs/pages/building-your-application/optimizing/images#priority)). We don't want images above the fold being lazy loaded at all.

if you're not still working on it don't worry, I can throw up a PR for this later today

**Comment by euanwm** [comment]
@rsbrowne - It's all yours buddyyyy.

**Comment by euanwm** [comment]
Linked to #388 

Closing
