### ISSUE TITLE
Increase sidebar padding / top border

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#246]
**Is your feature request related to a problem? Please describe.**
In the sidebar / menu the podium icon is obstructed by the header bar.

**Describe the solution you'd like**
Set padding so that the podium icon is shown in full.

**Additional context**
![image](https://github.com/euanwm/OpenWeightlifting/assets/69640923/21f23cfd-43c3-4148-bba7-d5f51f4bc327)

**Comment by Snowfall22** [comment]
interested

**Comment by VishalS-HK** [comment]
Can I be assigned this

**Comment by Surajit0573** [comment]
I would like to contribute to this issue! 
I will increase the top padding and will make it beautiful.
can you please assign me !!

**Comment by euanwm** [comment]
To avoid "issue squatting" during Hacktoberfest, issues are assigned retrospectively following a PR for first time contributors.
