### ISSUE TITLE
Prevent SmartLook from initialising locally

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#324]
**Is your feature request related to a problem? Please describe.**
SmartLook, that we use for analytics on the site, initializes during local testing and as a result it is recorded in the visitor data.

**Describe the solution you'd like**
A local/dev/test flag that disables the SmartLook tracker.

**Comment by joeysantia** [comment]
Hey! I'm interested in this one

**Comment by euanwm** [comment]
Closed by #325
