### ISSUE TITLE
Improve DB Checker

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#334]
**Is your feature request related to a problem? Please describe.**
The DB checker doesn't check that the achieved total matches up with the best snatch & clean & jerk made.

**Describe the solution you'd like**
Add additional check to the python/check_db.py script. It's used in the GitHub Actions workflow so should throw the necessary flag in the event of a bad result along with printing the filepath, and line.

**Additional context**
Example of a lift that was missed by the DB checker:
```
Event: IWF GRAND PRIX 5th RUSSIAN FEDERATION PRESIDENT'S CUP
Date: 2015-12-12
Gender: 94 kg Men
Name: VARDANIAN Norik
Bodyweight: 93.85
Sn1: 163
Sn2: 168
Sn3: 171
CJ1: 197
CJ2: -202
CJ3: 202
BestSn: 0
BestCJ: 0
Total: 0
Sinclair: 0
Federation: IWF
Instagram: 
```

**Comment by joeysantia** [comment]
Hey Euan! I'm interested in this one
