### ISSUE TITLE
Norway scraper tool returns bad values

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#338]
**Describe the bug**
When calculating the best scores, it is possible that a negative value is returned. This will when be deducted from the overall score when added to the total.

**To Reproduce**
1. Pull event ID 444 with the Norway scraping tool
2. Check result by Ingeborg Endresen

**Expected behavior**
A negative value implies a missed / not made lift and as result should be a zero value when being added to the total and should a lifter fail to a make a single lift during the session. The lowest value permissible in Best Snatch, Best C&J, and Best Total is ZERO.

**Additional context**
You can also use the event ID with the Norwegian Weightlifting Federation's results system to compare against:
- https://resultater.vektlofting.no/stevner/444

**Comment by euanwm** [comment]
@joeysantia - This is another easy one if you're interested in it.

**Comment by joeysantia** [comment]
@euanwm thanks, i'll check it out!
