### ISSUE TITLE
No redirect on https://openweightlifting.org/

### ISSUE THREAD

**Issue by sstangl** [euanwm/OpenWeightlifting#362]
When trying to visit the site, I often type `openweightlifting.org` into my browser's URL bar. This then auto-completes the protocol to the URL `https://openweightlifting.org/`, which fails to load, because it does not have a DNS entry. The site is only available if I type the full `www.openweightlifting.org`.

In Firefox and Chrome, `openweightlifting.org` fails to load. In Safari, it appears to initially fail to load, but then automatically tries prepending `www.`, which then succeeds.

I believe this requires an `A` record at the root, which requires a static IP address. I think you're using an AWS service that does not give a static address. One way around that could be to use an `A` record pointing to GitHub Pages, which would host a small auto-redirect to `www.openweightlifting.org`.

**Comment by euanwm** [comment]
@sstangl Should be a quick fix, looks like I didn't tick a box. Waiting for the changes to start working / breaking things.

**Comment by euanwm** [comment]
@sstangl Think that's it configured now. Let me know.

**Comment by sstangl** [comment]
Thanks! It works great.
