### ISSUE TITLE
frontend bug: "final" attempts to be renamed "3rd" attempts

### ISSUE THREAD

**Issue by haryoon** [euanwm/OpenWeightlifting#399]
**Describe the bug**

UI currently says "Snatch Final Attempt Rate", but a final attempt can be a second or first attempt. So UI text should change to "Snatch 3rd Attempt Rate" and "C&J 3rd Attempt Rate". "Opener" can also change to "1st attempt" but this still logically works.

**Comment by bnqctrn** [comment]
Can this ticket be added to the next sprint? It's a high priority for product to get this out ASAP

**Comment by euanwm** [comment]
@haryoon - More than happy for you to take this one on yourself, if you're interested. I'm currently working on quite a large work project so my time is limited.

@bnqctrn - Firstly, I don't know who you are. Secondly, _I am product_. Thirdly, we don't work in sprints, this is a community project where work is done as and when people are able to contribute.

**Comment by bnqctrn** [comment]
@euanwm Apologies, my KPI's are tied to this bug completion in Q3. Could you review and merge when ready? https://github.com/euanwm/OpenWeightlifting/pull/400

**Comment by euanwm** [comment]
I have no idea what is going on here and it has amused me greatly this evening.

**Comment by bnqctrn** [comment]
Thank you, management has been riding me so glad we were able to get this fixed. Will report back in our next retro

**Comment by euanwm** [comment]
Why do your management care?!?!?!

**Comment by bnqctrn** [comment]
@euanwm It's a management priority to get a CI/CD pipeline running, so a manual release may have to be packaged for this fix. DORA metrics are going to be super important moving forward as well

**Comment by euanwm** [comment]
@bnqctrn what the fuck are you on about now?
