### ISSUE TITLE
Leaderboard - Lifter Select

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#66]
**Is your feature request related to a problem? Please describe.**
Selecting a lifter also does hee-haw.

**Describe the solution you'd like**
When a lifter is selected, either the row expands or a popup appears. This will show the full lift information. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by euanwm** [comment]
Proposed line format as follows.
```
Position, Name, Country, Best Snatch, Best C&J, Total, Sinclair
```

**Comment by mountclear** [comment]
hello assign me this issue please
