### ISSUE TITLE
Docker Deployment

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#71]
**Is your feature request related to a problem? Please describe.**
Current Docker images are outdated and no longer work.

**Describe the solution you'd like**
Create a single docker image for deployment as this will allow minimal changes should we move from Heroku in the future

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rajat-tomar** [comment]
Hey @euanwm, I would like to work on this. Can you please assign this to me?

**Comment by euanwm** [comment]
For more detail - @rajat-tomar - it would be really great if we had an local development option as well.

Production mode - sets endpoint + CORS URL to the current website URL within the backend/serverMain.go and frontend/pages/index.jsx

Development mode - sets previously mentioned URLs to http://localhost:3000 / 8080.

**Comment by euanwm** [comment]
Use of docker environment variables from StackOverflow...

https://stackoverflow.com/questions/52103155/reading-an-environment-variable-in-react-which-was-set-by-docker

**Comment by rajat-tomar** [comment]
Yeah sure @euanwm, I'll build the Dockefile for both local and production

**Comment by rajat-tomar** [comment]
Hey @euanwm, is the backend server running fine for you? For me, it's listening on localhost:8080 though but gives me a 404 error.

**Comment by euanwm** [comment]
Hey, there currently isn't any endpoints assigned to the root URL. The only available endpoint is /leaderboard

**Comment by rajat-tomar** [comment]
/leaderboard endpoint I already tried but it didn't work.

**Comment by rajat-tomar** [comment]
in which file are your endpoints defined BTW??

**Comment by euanwm** [comment]
@rajat-tomar there's no documentation for the endpoints. I'll raise another issue for that.

I'm away to create a test endpoint - a simply GET request to allow for local testing.

**Comment by euanwm** [comment]
@rajat-tomar test endpoint (0.0.0.0:8080/test) available now.

Linked PR - #99
