### ISSUE TITLE
README Update - Backend

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#74]
**Is your feature request related to a problem? Please describe.**
Backend folder containing the Golang built API server does not have a README file.

**Describe the solution you'd like**
An initial README file that explains roughly what API server currently does.

**Describe alternatives you've considered**
N/A

**Additional context**
Improvement suggestions can also be raised during this time.

**Comment by kiranrokkam09** [comment]
hey @euanwm I would like to work on the issue. Can you assign it to me ?

**Comment by euanwm** [comment]
@kiranrokkam09 sure
