### ISSUE TITLE
Improve landing page

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#8]
OK, so React isn't as simple as I hoped it would be.

Landing page needs to show the top 100 men by total (default API call), along with continual loading, and the option to switch genders.

**Comment by euanwm** [comment]
@rsbrowne pagination would probably be easier to implement over infinite-scroll. I'm basing this off the 73 minutes of exposure i've had to React.

**Comment by rsbrowne** [comment]
Pagination is overrated as it starts getting weird with filters etc (which I intend on adding) so I'll do the show more button for now and we can come back to it and maybe do pagination later. How are you hosting this btw?

**Comment by euanwm** [comment]
@rsbrowne i'll update documentation on the API calls if it isn't that clear currently.  I haven't decided on a hosting option yet. I'm welcome to suggestions.

**Comment by rsbrowne** [comment]
@euanwm Feel free to assign this to me, I've been doing some work to get new front end tooling in place and I'll be in a better spot at the weekend to get more work done on the actual visuals
