### ISSUE TITLE
Add Discord Chat Link

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#82]
**Is your feature request related to a problem? Please describe.**
Low engagement from contributors.

**Describe the solution you'd like**
A Discord logo / hyperlink added next to the GitHub logo on the main page.

**Describe alternatives you've considered**
N/A

**Additional context**
Link URL:  https://discord.gg/kqnBqdktgr

**Comment by trishitchar** [comment]
can i work on here

**Comment by euanwm** [comment]
@trishitchar - Yeah sure, go ahead and join the channel. I'll assign the issue to you now.

**Comment by trishitchar** [comment]
Add link on github repo or on website?

**Comment by deepesh85b** [comment]
@euanwm 
Please assign this to If you wanna add any other link

**Comment by euanwm** [comment]
I would like a Discord logo with hyperlink on the website. The logo needs to sit to the immediate left of the GitHub logo. The photo below shows the portion where it will sit.

![Screenshot 2022-10-16 at 17 47 29](https://user-images.githubusercontent.com/69640923/196047747-d328070c-7cc4-465d-8c07-c8bb01dd5733.png)

**Comment by euanwm** [comment]
@deepesh85b - I'm still waiting on a PR to be raised for this. Feel free to raise one, first come first merged.

**Comment by euanwm** [comment]
Re-assigning to @mountclear

**Comment by mountclear** [comment]
hello assign to me

**Comment by euanwm** [comment]
Closed from #92
