### ISSUE TITLE
Improve PyLint Score

### ISSUE THREAD

**Issue by euanwm** [euanwm/OpenWeightlifting#87]
**Is your feature request related to a problem? Please describe.**
Current PyLint score is 8.18.

**Describe the solution you'd like**
A PyLint score of >9.0

**Describe alternatives you've considered**
N/A

**Additional context**
Must not result in a breaking change for backend_cli.py

See recent PyLint actions run for more details:
https://github.com/euanwm/OpenWeightlifting/actions/runs/3260823388/jobs/5354728255#step:5:1

**Comment by euanwm** [comment]
To be clear, all Python files are located within the python_tools folder. There is an abundance of code that is unused and could probably be removed.

**Comment by Kishore-abhimanyu** [comment]
Can you assign me this issue?
